image: Ubuntu

build: false

install:
- echo "Hello"
- git clone https://github.com/Goddard-Fortran-Ecosystem/pFUnit.git  /home/appveyor/projects/pFUnit
- cd pFUnit && mkdir b && cd b 
- cmake .. && make && make install && cd ../../

test_script:
- echo "HEJSAN"
- ls /home/appveyor/projects/pFUnit/b