image:
- ubuntu

build: on

install:
- cmd: echo "Hello"
- cmd: git clone https://github.com/Goddard-Fortran-Ecosystem/pFUnit.git  /home/appveyor/projects/pFUnit
- cmd: cd pFUnit && mkdir b && cd b 
- cmd: cmake .. && make && make install && cd ../../

test_script:
- echo "HEJSAN"
- ls /home/appveyor/projects/pFUnit/b